platform :osx
link_with 'GDChannel', 'GDChannelTests'

# pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git'
# pod 'J2ObjC', :path => '~/dev/tools/lib/j2objc/J2ObjC.podspec'
pod 'GDJson', :git => 'https://github.com/goodow/realtime-json.git'

pod 'GDChannel', :path => '..'
